Repository DIT113-V22/group-08, pull requests merged in 2022-05, with the labels that each got.

#35 #23 update of the arduino car, MQTT connection and topics
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/MovementConnection.java
  arduino/smartcar/smartcar.ino
Labels: #Sprint2

#36 Splash animation and app icon
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/IntroSplashAnimation.java
  Android/islandRush/app/src/main/res/anim/car_start_animation.xml
  Android/islandRush/app/src/main/res/anim/start_animation.xml
  Android/islandRush/app/src/main/res/drawable-v24/down_button.png
  Android/islandRush/app/src/main/res/drawable-v24/left_button.png
  Android/islandRush/app/src/main/res/drawable-v24/right_button.png
  Android/islandRush/app/src/main/res/drawable-v24/stop_button.png
  Android/islandRush/app/src/main/res/drawable-v24/up_button.png
  Android/islandRush/app/src/main/res/drawable/animation_background.xml
  Android/islandRush/app/src/main/res/drawable/bil.png
  Android/islandRush/app/src/main/res/drawable/logo.png
  Android/islandRush/app/src/main/res/drawable/palm.png
  Android/islandRush/app/src/main/res/layout-land/activity_intro_splash_animation.xml
  Android/islandRush/app/src/main/res/layout/activity_intro_splash_animation.xml
  Android/islandRush/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/islandRush/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/islandRush/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Android/islandRush/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Android/islandRush/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Android/islandRush/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Android/islandRush/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Android/islandRush/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Android/islandRush/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Android/islandRush/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Android/islandRush/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Android/islandRush/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Android/islandRush/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Android/islandRush/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Android/islandRush/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Android/islandRush/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Android/islandRush/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Android/islandRush/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Android/islandRush/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Android/islandRush/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Android/islandRush/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Android/islandRush/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Android/islandRush/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Android/islandRush/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Android/islandRush/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Android/islandRush/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Android/islandRush/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: #Sprint2

#47 Joystick backend and stop button. Including display improvements
  Android/islandRush/app/build.gradle
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/BrokerConnection.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlChoice.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/IntroSplashAnimation.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Joystick.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/MainActivity.java
  Android/islandRush/app/src/main/res/drawable/ic_baseline_speed_24.xml
  Android/islandRush/app/src/main/res/drawable/ic_person_vector.xml
  Android/islandRush/app/src/main/res/drawable/main_buttons.xml
  Android/islandRush/app/src/main/res/layout-land/activity_control_choice.xml
  Android/islandRush/app/src/main/res/layout-land/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout-land/activity_intro_splash_animation.xml
  Android/islandRush/app/src/main/res/layout-land/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout-land/activity_main.xml
  Android/islandRush/app/src/main/res/layout/activity_control_choice.xml
  Android/islandRush/app/src/main/res/layout/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout/activity_intro_splash_animation.xml
  Android/islandRush/app/src/main/res/layout/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout/activity_main.xml
  Android/islandRush/app/src/main/res/values/strings.xml
  Mod/dependencies/jog_kusa.png.import
  Mod/dependencies/mendrill01.obj.import
  Mod/dependencies/mendrill01.png.import
  Mod/dependencies/resort_0_tex.png.import
  Mod/dependencies/water_diffuse.png.import
  Mod/dependencies/water_normal.png.import
  Mod/dependencies/water_uv_offset.png.import
  Mod/dependencies/wuhu.obj.import
  arduino/smartcar/smartcar.ino
Labels: #Sprint2

#45 Update Readme.md
  README.md
Labels: documentation

#51 Leaderboard UX
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlChoice.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Direction.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Leaderboard1.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Leaderboard2.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/MainActivity.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/MqttClient.java
  Android/islandRush/app/src/main/res/drawable/first_medal.png
  Android/islandRush/app/src/main/res/drawable/rush_ireland.png
  Android/islandRush/app/src/main/res/drawable/second_medal.png
  Android/islandRush/app/src/main/res/drawable/third_medal.png
  Android/islandRush/app/src/main/res/drawable/vector.xml
  Android/islandRush/app/src/main/res/layout/activity_leaderboard1.xml
  Android/islandRush/app/src/main/res/layout/activity_leaderboard2.xml
  README.md
Labels: #Sprint2

#50 UI test for app navigation and Android CI update
  .github/dod.yaml
  .github/workflows/android-ci.yml
  .github/workflows/dod-checker.yaml
  Android/islandRush/app/build.gradle
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ActivityTestSuite.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ControlChoiceTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ControlPadTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ExampleInstrumentedTest.java
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/JoystickTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/LeaderboardTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/MainActivityTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ToastMatcher.kt
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/BrokerConnection.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlChoice.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Direction.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Joystick.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Leaderboard.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Leaderboard1.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Leaderboard2.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/MainActivity.java
  Android/islandRush/app/src/main/res/drawable-v24/background1.xml
  Android/islandRush/app/src/main/res/drawable-v24/background2.xml
  Android/islandRush/app/src/main/res/drawable/animation_background.xml
  Android/islandRush/app/src/main/res/drawable/black_circle_button.xml
  Android/islandRush/app/src/main/res/layout-land/activity_control_choice.xml
  Android/islandRush/app/src/main/res/layout-land/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout-land/activity_intro_splash_animation.xml
  Android/islandRush/app/src/main/res/layout-land/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout-land/activity_leaderboard.xml
  Android/islandRush/app/src/main/res/layout-land/activity_main.xml
  Android/islandRush/app/src/main/res/layout-land/fragment_leaderboard1.xml
  Android/islandRush/app/src/main/res/layout-land/fragment_leaderboard2.xml
  Android/islandRush/app/src/main/res/layout/activity_control_choice.xml
  Android/islandRush/app/src/main/res/layout/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout/activity_intro_splash_animation.xml
  Android/islandRush/app/src/main/res/layout/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout/activity_leaderboard.xml
  Android/islandRush/app/src/main/res/layout/activity_main.xml
  Android/islandRush/app/src/main/res/layout/fragment_leaderboard1.xml
  Android/islandRush/app/src/main/res/layout/fragment_leaderboard2.xml
  Android/islandRush/app/src/main/res/values-night/themes.xml
  Android/islandRush/app/src/main/res/values/colors.xml
  Android/islandRush/app/src/main/res/values/strings.xml
  Android/islandRush/app/src/main/res/values/themes.xml
  Android/islandRush/app/src/test/java/com/quinstedt/islandRush/ExampleUnitTest.java
  Android/islandRush/build.gradle
Labels: #Sprint3

#64 Revert "Build godot project on CI"
  Godot CI.yml
Labels: #Sprint3

#67 Timer
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/BrokerConnection.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Joystick.java
  Android/islandRush/app/src/main/res/layout-land/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout-land/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout/activity_joystick.xml
Labels: #Sprint3

#68 Animation for the ending of game
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/MainActivityTest.kt
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/LeaderboardAnimation.java
  Android/islandRush/app/src/main/res/anim/car_move.xml
  Android/islandRush/app/src/main/res/anim/slide_background.xml
  Android/islandRush/app/src/main/res/anim/slide_in_text.xml
  Android/islandRush/app/src/main/res/anim/slide_out_text.xml
  Android/islandRush/app/src/main/res/layout-land/activity_leaderboard_animation.xml
  Android/islandRush/app/src/main/res/layout/activity_leaderboard_animation.xml
Labels: #Sprint3

#80 Connecting the components for the finish of the race
  .gitignore
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ActivityTestSuite.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ControlChoiceTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ControlPadTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/JoystickTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/LeaderboardTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/MainActivityTest.kt
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/BrokerConnection.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/GlobalData.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Joystick.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/LeaderboardAnimation.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/MainActivity.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Utils.java
  Android/islandRush/app/src/main/res/layout-land/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout-land/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout-land/activity_leaderboard_animation.xml
  Android/islandRush/app/src/main/res/layout/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout/activity_leaderboard_animation.xml
Labels: #Sprint3, Connecting components, #Sprint4

#81 Added pause button for joystick and control pad
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/GlobalData.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Joystick.java
  Android/islandRush/app/src/main/res/layout-land/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout-land/activity_joystick.xml
  Android/islandRush/app/src/main/res/layout/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout/activity_joystick.xml
Labels: #Sprint4

#84 Update README.md
  README.md
Labels: documentation, #Sprint4

#83 Credits Screen
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/CreditsActivity.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/MainActivity.java
  Android/islandRush/app/src/main/res/anim/credits.xml
  Android/islandRush/app/src/main/res/layout-land/activity_credits.xml
  Android/islandRush/app/src/main/res/layout-land/activity_main.xml
  Android/islandRush/app/src/main/res/layout/activity_credits.xml
  Android/islandRush/app/src/main/res/layout/activity_main.xml
Labels: #Sprint4

#87 Fixed the speedometer bug while using the Reset button
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/activityClasses/MainActivityTest.kt
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/Joystick.java
  Android/islandRush/app/src/main/res/layout/activity_main.xml
Labels: enhancement

#93 Game mode choice
  Android/islandRush/app/build.gradle
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/activityClasses/ControlPadTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/activityClasses/JoystickTest.kt
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/activityClasses/MainActivityTest.kt
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/BrokerConnection.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/Utils.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/ControlChoice.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/Joystick.java
  Android/islandRush/app/src/main/res/drawable/ic_off.xml
  Android/islandRush/app/src/main/res/drawable/ic_on.xml
  Android/islandRush/app/src/main/res/drawable/thumb.xml
  Android/islandRush/app/src/main/res/drawable/thumb_off.xml
  Android/islandRush/app/src/main/res/drawable/thumb_on.xml
  Android/islandRush/app/src/main/res/drawable/track.xml
  Android/islandRush/app/src/main/res/layout-land/activity_control_choice.xml
  Android/islandRush/app/src/main/res/layout/activity_control_choice.xml
  Android/islandRush/app/src/main/res/layout/activity_control_pad.xml
  Android/islandRush/app/src/main/res/layout/activity_joystick.xml
Labels: #Sprint4, UserStories

#92 Adding Mood CI tag in README
  README.md
Labels: documentation

#88 How to play Instructions and button Animation
  Android/islandRush/app/src/androidTest/java/com/quinstedt/islandRush/ActivityTestSuite.kt
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/ControlChoice.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/CreditsActivity.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/Joystick.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/MainActivity.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/Scoreboard.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/instructionClasses/CheckLeaderboard.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/instructionClasses/ControlsInstruction.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/instructionClasses/GameModes.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/instructionClasses/GettingStarted.java
  Android/islandRush/app/src/main/res/anim/scale_down.xml
  Android/islandRush/app/src/main/res/anim/scale_up.xml
  Android/islandRush/app/src/main/res/drawable/control_land.png
  Android/islandRush/app/src/main/res/drawable/control_portrait.png
  Android/islandRush/app/src/main/res/drawable/leaderboard.png
  Android/islandRush/app/src/main/res/drawable/main_menu.png
  Android/islandRush/app/src/main/res/drawable/main_menu_land.png
  Android/islandRush/app/src/main/res/layout-land/activity_check_leaderboard.xml
  Android/islandRush/app/src/main/res/layout-land/activity_controls_instruction.xml
  Android/islandRush/app/src/main/res/layout-land/activity_credits.xml
  Android/islandRush/app/src/main/res/layout-land/activity_game_modes.xml
  Android/islandRush/app/src/main/res/layout-land/activity_getting_started.xml
  Android/islandRush/app/src/main/res/layout-land/activity_main.xml
  Android/islandRush/app/src/main/res/layout/activity_check_leaderboard.xml
  Android/islandRush/app/src/main/res/layout/activity_controls_instruction.xml
  Android/islandRush/app/src/main/res/layout/activity_credits.xml
  Android/islandRush/app/src/main/res/layout/activity_game_modes.xml
  Android/islandRush/app/src/main/res/layout/activity_getting_started.xml
  Android/islandRush/app/src/main/res/layout/activity_main.xml
  Android/islandRush/app/src/main/res/layout/activity_scoreboard.xml
  Android/islandRush/app/src/main/res/values/strings.xml
Labels: #Sprint3, #Sprint4

#96 adding a screen before the race
  Android/islandRush/app/src/main/AndroidManifest.xml
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/SplashScreens/BeforeRaceStart.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/SplashScreens/LeaderboardAnimation.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/ControlChoice.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/ControlPad.java
  Android/islandRush/app/src/main/java/com/quinstedt/islandRush/activityClasses/Joystick.java
  Android/islandRush/app/src/main/res/drawable/black_rectangel.xml
  Android/islandRush/app/src/main/res/drawable/finishline_and_car.png
  Android/islandRush/app/src/main/res/layout-land/activity_before_race_start.xml
  Android/islandRush/app/src/main/res/layout/activity_before_race_start.xml
  Android/islandRush/app/src/main/res/layout/activity_scoreboard.xml
  arduino/finish_line/finish_line.ino
Labels: enhancement

#91 Update Readme.md
  README.md
Labels: documentation, Assigment, #Sprint4
